# name: Build modelbox rockchip images
# on:
#   push:
#     branches:
#       - main

# jobs:
#   complie_rockchip_rknnrt_build_ubuntu:
#     #runs-on: ubuntu-20.04
#     runs-on: [self-hosted, Linux, ARM64]
#     outputs:
#       IMAGE_NAME_DEV: ${{ steps.env.outputs.IMAGE_NAME_DEV }}
#       IMAGE_VERSION: ${{ steps.env.outputs.IMAGE_VERSION }}
#     name: Build on ${{ matrix.distro }} ${{ matrix.arch }}

#     strategy:
#       matrix:
#         include:
#           - arch: aarch64
#             distro: ubuntu20.04
#     steps:
#       - name: Set-env
#         id: env
#         run: |
#           echo "::set-output name=IMAGE_NAME_DEV::fujialin/fujialin-develop-rockchip-rknnrt-ubuntu-aarch64"
#           echo "::set-output name=IMAGE_VERSION::1.0.1"
#       - run: echo "the docker name is ${{ steps.env.outputs.IMAGE_NAME_DEV }}."
#       - run: echo "the docker version is ${{ steps.env.outputs.IMAGE_VERSION }}."
#       - name: Checkout
#         uses: actions/checkout@v3
#       - name: Set up Docker Buildx
#         uses: docker/setup-buildx-action@v1
#       - name: Login to DockerHub
#         uses: docker/login-action@v1
#         with:
#           username: ${{ secrets.DOCKERHUB_USERNAME }}
#           password: ${{ secrets.DOCKERHUB_TOKEN }}
#       - run: echo "the arch is ${{ runner.arch }}."
#       - name: Download for rockchip package
#         run: ./docker/prepare_for_rockchip.sh
#         shell: bash
#       - name: Build and Push
#         uses: docker/build-push-action@v2
#         with:
#           push: true
#           context: .
#           file: docker/Dockerfile.rknnrt.build.ubuntu
#           tags: |
#             ${{ steps.env.outputs.IMAGE_NAME_DEV }}:latest
#             ${{ steps.env.outputs.IMAGE_NAME_DEV }}:${{ steps.env.outputs.IMAGE_VERSION }}