name: actions test
on:
  push:
    branches:
      - main

jobs:
  my_first_job:
    name: my first job
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        include:
          - arch: aarch64
            distro: ubuntu-20.04
    steps:
      - name: print a greeting
        env:
          MY_VAR: hi there! my name is
          FIRST_NAME: Mona
          MIDDLE_NAME: The
          LAST_NAME: Octocat
        run: |
          echo $MY_VAR $FIRST_NAME $MIDDLE_NAME $LAST_NAME
      - run: echo "the job was automatically triggered by a ${{ github.envent_name }} envent."
      - run: echo "the job is now running on a ${{ runner.os }} server hosted by github!"
      - run: echo "the name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - run: echo "the workspace is ${{ github.workspace }}."
      - run: echo "the job's status is ${{ job.status }}."
      - run: echo "the arch is ${{ runner.arch }}."
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
